// <auto-generated />
using System;
using InventoryManager.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManager.EntityFramework.Migrations
{
    [DbContext(typeof(InventoryManagerDbContext))]
    [Migration("20201208014636_UpdatedDatabaseSchemaToNewModel")]
    partial class UpdatedDatabaseSchemaToNewModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("InventoryManager.Domain.Models.ContainerItems", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Containerid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Itemid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Containerid");

                    b.HasIndex("Itemid");

                    b.ToTable("ContainerItems");
                });

            modelBuilder.Entity("InventoryManager.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("InventoryManager.Domain.Models.Container", b =>
                {
                    b.HasBaseType("InventoryManager.Domain.Models.Item");

                    b.Property<double>("CurrentCarryCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumCarryCapacity")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("InventoryManager.Domain.Models.ContainerItems", b =>
                {
                    b.HasOne("InventoryManager.Domain.Models.Container", null)
                        .WithMany("Inventory")
                        .HasForeignKey("Containerid");

                    b.HasOne("InventoryManager.Domain.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Itemid");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("InventoryManager.Domain.Models.Container", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
